---
# tasks file for ansible-role-libvirtd
- name: Install packages
  become: yes
  package:
    name:
      - "@virtualization"
      - virt-top

- name: Force systemd to reread config, enable and start service libvirtd
  become: yes
  systemd:
    name: libvirtd
    state: restarted
    daemon_reload: yes
    enabled: yes
